version: "3.8"
services:
  mongodb:
    image: mongo
    container_name: mongodb
    networks:
      - mern-network

  server:
    build: ./server
    container_name: server
    ports:
      - "9000:9000"
    networks:
      - mern-network
    environment:
      MONGO_URI: mongodb://mongodb:27017/mern
    depends_on:
      - mongodb

  client:
    build: ./client
    container_name: client
    ports:
      - "3000:3000"
    networks:
      - mern-network
    depends_on:
      - server

networks:
  mern-network:
    driver: bridge
